// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrU-eOhAmvdmAd5zq_JGRvQNnL8ldO4-o',
    appId: '1:404710439736:web:4ea76d3c005d5a3cb01fcd',
    messagingSenderId: '404710439736',
    projectId: 'iwms-2ff58',
    authDomain: 'iwms-2ff58.firebaseapp.com',
    databaseURL: 'https://iwms-2ff58-default-rtdb.firebaseio.com',
    storageBucket: 'iwms-2ff58.appspot.com',
    measurementId: 'G-761PEJ2Q44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUKyGVY5V6yvDy0iVsTG7ec4uy-BDOTE',
    appId: '1:404710439736:android:ce32dc4a713accd8b01fcd',
    messagingSenderId: '404710439736',
    projectId: 'iwms-2ff58',
    databaseURL: 'https://iwms-2ff58-default-rtdb.firebaseio.com',
    storageBucket: 'iwms-2ff58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwidR6nxz7cRU26YPHBnA8JCbMZs-NRZU',
    appId: '1:404710439736:ios:c5e114720b58da14b01fcd',
    messagingSenderId: '404710439736',
    projectId: 'iwms-2ff58',
    databaseURL: 'https://iwms-2ff58-default-rtdb.firebaseio.com',
    storageBucket: 'iwms-2ff58.appspot.com',
    iosBundleId: 'com.example.iwm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwidR6nxz7cRU26YPHBnA8JCbMZs-NRZU',
    appId: '1:404710439736:ios:3b09859168728d0db01fcd',
    messagingSenderId: '404710439736',
    projectId: 'iwms-2ff58',
    databaseURL: 'https://iwms-2ff58-default-rtdb.firebaseio.com',
    storageBucket: 'iwms-2ff58.appspot.com',
    iosBundleId: 'com.example.iwm.RunnerTests',
  );
}
